#!/usr/bin/env python3
"""
Knowledge graph for research paper source extracts.

Uses LightRAG to build a queryable knowledge graph from research/sources/*.md files.
All LLM and embedding calls go through OpenRouter (OPENROUTER_API_KEY env var).

Ingestion priority (highest to lowest quality):
    1. research/sources/*.md       — curated source extracts
    2. research/prepared/**/*.md   — structured claims, methodology, and assumption docs
                                     (generated by reviewer-kb.py)
    3. attachments/parsed/*.md     — Docling-parsed full-text PDFs
    4. attachments/*.pdf           — raw PDF fallback (pymupdf extraction)

Usage:
    # Batch ingestion (legacy — blocks until complete)
    python scripts/knowledge.py build                        # Build/update graph from sources
    python scripts/knowledge.py update                       # Incremental update (new/changed files only)

    # Queue-based streaming ingestion (preferred — non-blocking)
    python scripts/knowledge.py serve                        # Start background worker (one per project)
    python scripts/knowledge.py enqueue file [file...]       # Queue files for ingestion (instant)
    python scripts/knowledge.py enqueue --reindex file...    # Force re-ingestion of already-processed files
    python scripts/knowledge.py status                       # Show queue: pending/done/failed, worker alive?
    python scripts/knowledge.py drain [--timeout N]          # Block until queue is empty
    python scripts/knowledge.py stop                         # Graceful worker shutdown

    # Querying (works against whatever has been ingested so far)
    python scripts/knowledge.py query "question"             # Freeform semantic search
    python scripts/knowledge.py contradictions               # Find conflicting claims
    python scripts/knowledge.py evidence-for "claim"         # Sources supporting a claim
    python scripts/knowledge.py evidence-against "claim"     # Sources challenging a claim
    python scripts/knowledge.py entities                     # List extracted entities
    python scripts/knowledge.py relationships "entity"       # Show entity connections
    python scripts/knowledge.py coverage "document.md"       # Check entity coverage in a document
"""

import os
import subprocess
import sys


def _ensure_venv():
    """Re-exec this script inside the research-agent .venv if needed."""
    script_path = os.path.realpath(__file__)
    scripts_dir = os.path.dirname(script_path)
    repo_root = os.path.normpath(os.path.join(scripts_dir, "..", ".."))
    venv_dir = os.path.join(repo_root, ".venv")
    venv_python = os.path.join(venv_dir, "bin", "python3")

    # Check if we're running inside the project's .venv by looking at
    # sys.prefix, not sys.executable (all venvs symlink to the same
    # underlying Python binary, so realpath comparison doesn't work).
    if os.path.realpath(sys.prefix) == os.path.realpath(venv_dir):
        return

    ensure_script = os.path.join(scripts_dir, "ensure-venv.sh")
    if os.path.exists(ensure_script):
        subprocess.run(["bash", ensure_script], check=True,
                       stdout=subprocess.DEVNULL)

    if os.path.exists(venv_python):
        os.execv(venv_python, [venv_python] + sys.argv)


if __name__ == "__main__":
    _ensure_venv()

import argparse
import asyncio
import enum
import json
import re
import signal
from dataclasses import dataclass
from datetime import datetime, timezone
from functools import partial
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

WORKING_DIR = "research/knowledge"
SOURCES_DIR = "research/sources"
PREPARED_DIR = "research/prepared"
ATTACHMENTS_DIR = "attachments"
PARSED_DIR = "attachments/parsed"
LOG_FILE = "research/log.md"
CONTRADICTIONS_FILE = "research/knowledge_contradictions.md"
LAST_BUILD_FILE = os.path.join(WORKING_DIR, ".last_build")
CACHE_DIR = os.path.join(WORKING_DIR, ".cache")
QUEUE_FILE = os.path.join(WORKING_DIR, ".queue.jsonl")
PROGRESS_FILE = os.path.join(WORKING_DIR, ".queue_progress.json")
WORKER_PID_FILE = os.path.join(WORKING_DIR, ".worker.pid")
WORKER_LOG_FILE = os.path.join(WORKING_DIR, "worker.log")

# --- Models ---
# Ingestion model: used for entity extraction and merge summarization during build/update.
# Needs: fast, cheap, good at structured extraction. Flash-tier models excel here.
LLM_MODEL = os.environ.get("LIGHTRAG_LLM_MODEL", "google/gemini-3-flash-preview")
# Query model: used when answering questions against the graph. Falls back to LLM_MODEL.
# Needs: reasoning, synthesis, nuanced writing. Smarter models pay off here.
QUERY_LLM_MODEL = os.environ.get("LIGHTRAG_QUERY_LLM_MODEL", "")
EMBEDDING_MODEL = os.environ.get("LIGHTRAG_EMBEDDING_MODEL", "qwen/qwen3-embedding-8b")
EMBEDDING_DIM = int(os.environ.get("LIGHTRAG_EMBEDDING_DIM", "4096"))
EMBEDDING_LENGTH = int(os.environ.get("LIGHTRAG_EMBEDDING_LENGTH", "32000"))
OPENROUTER_BASE_URL = os.environ.get("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")

# --- Concurrency ---
# Total concurrent LLM calls ≈ MAX_PARALLEL_INSERT × LLM_MAX_ASYNC.
# Override via env vars if your API plan supports higher throughput.
MAX_PARALLEL_INSERT = int(os.environ.get("LIGHTRAG_MAX_PARALLEL_INSERT", "20"))
LLM_MAX_ASYNC = int(os.environ.get("LIGHTRAG_MAX_ASYNC", "32"))
EMBEDDING_BATCH_NUM = int(os.environ.get("LIGHTRAG_EMBEDDING_BATCH_NUM", "16"))
EMBEDDING_FUNC_MAX_ASYNC = int(os.environ.get("LIGHTRAG_EMBEDDING_FUNC_MAX_ASYNC", "16"))

# --- Chunking ---
# Larger chunks = fewer entities per document = fewer merge operations.
CHUNK_TOKEN_SIZE = int(os.environ.get("LIGHTRAG_CHUNK_TOKEN_SIZE", "8000"))
CHUNK_OVERLAP_TOKEN_SIZE = int(os.environ.get("LIGHTRAG_CHUNK_OVERLAP_TOKEN_SIZE", "100"))
TIKTOKEN_MODEL_NAME = os.environ.get("LIGHTRAG_TIKTOKEN_MODEL", "gpt-4o-mini")

# --- Entity extraction ---
# max_gleaning: how many extra passes over ambiguous text to extract more entities (0=one pass).
ENTITY_EXTRACT_MAX_GLEANING = int(os.environ.get("LIGHTRAG_MAX_GLEANING", "1"))
# Max tokens fed into a single extraction call. Longer docs get split.
MAX_EXTRACT_INPUT_TOKENS = int(os.environ.get("LIGHTRAG_MAX_EXTRACT_INPUT_TOKENS", "20480"))
# After this many descriptions are merged for an entity, LLM re-summarizes instead of concatenating.
FORCE_LLM_SUMMARY_ON_MERGE = int(os.environ.get("LIGHTRAG_FORCE_SUMMARY_ON_MERGE", "20"))
# Entity types the extractor looks for.  JSON list or comma-separated.
_DEFAULT_ENTITY_TYPES = "Person,Creature,Organization,Location,Event,Concept,Method,Content,Data,Artifact,NaturalObject"
_raw_entity_types = os.environ.get("LIGHTRAG_ENTITY_TYPES", "")
ENTITY_TYPES = [t.strip() for t in _raw_entity_types.split(",") if t.strip()] if _raw_entity_types else None

# --- Summary generation ---
# Controls LLM-generated entity/relation summaries during graph construction.
SUMMARY_MAX_TOKENS = int(os.environ.get("LIGHTRAG_SUMMARY_MAX_TOKENS", "1200"))
SUMMARY_CONTEXT_SIZE = int(os.environ.get("LIGHTRAG_SUMMARY_CONTEXT_SIZE", "12000"))
SUMMARY_LENGTH_RECOMMENDED = int(os.environ.get("LIGHTRAG_SUMMARY_LENGTH_RECOMMENDED", "600"))
SUMMARY_LANGUAGE = os.environ.get("LIGHTRAG_SUMMARY_LANGUAGE", "English")

# --- Query & retrieval defaults ---
# These set defaults on the LightRAG instance. Per-query overrides via QueryParam.
TOP_K = int(os.environ.get("LIGHTRAG_TOP_K", "40"))
CHUNK_TOP_K = int(os.environ.get("LIGHTRAG_CHUNK_TOP_K", "20"))
MAX_ENTITY_TOKENS = int(os.environ.get("LIGHTRAG_MAX_ENTITY_TOKENS", "6000"))
MAX_RELATION_TOKENS = int(os.environ.get("LIGHTRAG_MAX_RELATION_TOKENS", "8000"))
MAX_TOTAL_TOKENS = int(os.environ.get("LIGHTRAG_MAX_TOTAL_TOKENS", "30000"))
COSINE_THRESHOLD = float(os.environ.get("LIGHTRAG_COSINE_THRESHOLD", "0.2"))
RELATED_CHUNK_NUMBER = int(os.environ.get("LIGHTRAG_RELATED_CHUNK_NUMBER", "5"))
# "VECTOR" (embedding similarity) or "WEIGHT" (graph-edge weight).
KG_CHUNK_PICK_METHOD = os.environ.get("LIGHTRAG_KG_CHUNK_PICK_METHOD", "VECTOR")
# Default query mode used by the `query` subcommand: local|global|hybrid|naive|mix.
DEFAULT_QUERY_MODE = os.environ.get("LIGHTRAG_DEFAULT_QUERY_MODE", "hybrid")

# --- Graph size limits ---
MAX_GRAPH_NODES = int(os.environ.get("LIGHTRAG_MAX_GRAPH_NODES", "10000"))
MAX_SOURCE_IDS_PER_ENTITY = int(os.environ.get("LIGHTRAG_MAX_SOURCE_IDS_PER_ENTITY", "300"))
MAX_SOURCE_IDS_PER_RELATION = int(os.environ.get("LIGHTRAG_MAX_SOURCE_IDS_PER_RELATION", "300"))
SOURCE_IDS_LIMIT_METHOD = os.environ.get("LIGHTRAG_SOURCE_IDS_LIMIT_METHOD", "FIFO")
MAX_FILE_PATHS = int(os.environ.get("LIGHTRAG_MAX_FILE_PATHS", "10000"))

# --- Caching ---
ENABLE_LLM_CACHE = os.environ.get("LIGHTRAG_ENABLE_LLM_CACHE", "true").lower() == "true"
ENABLE_LLM_CACHE_FOR_EXTRACT = os.environ.get("LIGHTRAG_ENABLE_LLM_CACHE_FOR_EXTRACT", "true").lower() == "true"
EMBEDDING_CACHE_ENABLED = os.environ.get("LIGHTRAG_EMBEDDING_CACHE_ENABLED", "true").lower() == "true"
EMBEDDING_CACHE_SIMILARITY = float(os.environ.get("LIGHTRAG_EMBEDDING_CACHE_SIMILARITY", "0.95"))

# --- Timeouts (seconds) --- full PDFs need more time than short extracts.
LLM_TIMEOUT = int(os.environ.get("LIGHTRAG_LLM_TIMEOUT", "600"))
EMBEDDING_TIMEOUT = int(os.environ.get("LIGHTRAG_EMBEDDING_TIMEOUT", "600"))

# --- Worker tunables ---
WORKER_POLL_INTERVAL = float(os.environ.get("LIGHTRAG_WORKER_POLL_INTERVAL", "2.0"))
WORKER_STOP_TIMEOUT = int(os.environ.get("LIGHTRAG_WORKER_STOP_TIMEOUT", "30"))
DRAIN_POLL_INTERVAL = float(os.environ.get("LIGHTRAG_DRAIN_POLL_INTERVAL", "5.0"))
# How many pending files to batch into a single ainsert() call.
# Higher = better utilization of max_parallel_insert (documents processed concurrently).
# 1 = legacy one-at-a-time behavior.
WORKER_BATCH_SIZE = int(os.environ.get("LIGHTRAG_WORKER_BATCH_SIZE", "10"))

# --- Storage backend: "file" (default) or "opensearch" ---
LIGHTRAG_STORAGE = os.environ.get("LIGHTRAG_STORAGE", "file")
if LIGHTRAG_STORAGE not in ("file", "opensearch"):
    print(f"Error: Invalid LIGHTRAG_STORAGE={LIGHTRAG_STORAGE!r}. Must be 'file' or 'opensearch'.", file=sys.stderr)
    sys.exit(1)


def get_api_key():
    """Get OpenRouter API key from environment. Exits with code 1 on missing key."""
    key = os.environ.get("OPENROUTER_API_KEY")
    if not key:
        print("Error: OPENROUTER_API_KEY environment variable not set.", file=sys.stderr)
        print("Get a key at https://openrouter.ai/keys", file=sys.stderr)
        sys.exit(1)
    return key


def check_api_key_available():
    """Check if OPENROUTER_API_KEY is set. Returns the key or None."""
    return os.environ.get("OPENROUTER_API_KEY")


def _graceful_exit_no_api_key(command_name: str):
    """Print a user-friendly message and exit 0 when API key is missing.

    Used by commands that should degrade gracefully (exit 0) rather than
    crash, so that bash && chains and pipeline orchestration continue.
    """
    print(f"Knowledge graph {command_name}: skipped (OPENROUTER_API_KEY not set).")
    print("Set the key to enable knowledge graph features: export OPENROUTER_API_KEY=your-key")
    print("Get a key at https://openrouter.ai/keys")
    sys.exit(0)


def log_operation(operation: str, details: dict):
    """Append an entry to research/log.md."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    entry = f"\n### {timestamp} — Knowledge Graph {operation}\n"
    for key, value in details.items():
        entry += f"- **{key}**: {value}\n"
    log_path = Path(LOG_FILE)
    if log_path.exists():
        with open(log_path, "a") as f:
            f.write(entry)


def _save_build_timestamp():
    """Save current timestamp as last build time."""
    Path(LAST_BUILD_FILE).write_text(
        datetime.now(timezone.utc).isoformat(), encoding="utf-8"
    )


def _invalidate_cache():
    """Delete query cache (called after build/update)."""
    import shutil

    cache_path = Path(CACHE_DIR)
    if cache_path.exists():
        shutil.rmtree(cache_path)


def _get_cache_path(query: str, mode: str) -> Path:
    """Get cache file path for a query."""
    import hashlib

    key = hashlib.sha256(f"{query}|{mode}".encode()).hexdigest()[:32]
    return Path(CACHE_DIR) / f"{key}.txt"


def _get_query_model_func():
    """Return an LLM function for query-time if QUERY_LLM_MODEL is set, else None."""
    if not QUERY_LLM_MODEL or QUERY_LLM_MODEL == LLM_MODEL:
        return None
    from lightrag.llm.openai import openai_complete
    return partial(
        openai_complete,
        model=QUERY_LLM_MODEL,
        base_url=OPENROUTER_BASE_URL,
        api_key=get_api_key(),
    )


# ---------------------------------------------------------------------------
# Query pattern classification
# ---------------------------------------------------------------------------

class QueryPattern(enum.Enum):
    """Classification of user query intent for strategy selection."""
    SPECIFIC_PAPER = "specific_paper"
    CONCEPT_EXPLORATION = "concept_exploration"
    EVIDENCE = "evidence"
    CONTRADICTION = "contradiction"
    BROAD_SURVEY = "broad_survey"
    DEFAULT = "default"


_PATTERN_RULES: list[tuple[QueryPattern, list[re.Pattern]]] = [
    (QueryPattern.SPECIFIC_PAPER, [
        re.compile(r"""['"].+['"]"""),               # quoted titles
        re.compile(r"\bpaper\s+by\s+", re.I),        # "paper by Author"
        re.compile(r"\b[a-z]+\d{4}[a-z]*\b"),        # bibtex keys like vaswani2017
    ]),
    (QueryPattern.EVIDENCE, [
        re.compile(r"\bevidence\s+(for|against|supporting|contradicting)\b", re.I),
        re.compile(r"\bsupports?\s+(the\s+)?claim\b", re.I),
    ]),
    (QueryPattern.CONTRADICTION, [
        re.compile(r"\bcontradiction", re.I),
        re.compile(r"\bconflicts?\s+(with\b|claim)", re.I),
        re.compile(r"\bdisagree\b", re.I),
        re.compile(r"\btension\s+between\b", re.I),
    ]),
    (QueryPattern.CONCEPT_EXPLORATION, [
        re.compile(r"\bwhat\s+(is|are)\b", re.I),
        re.compile(r"\bapproaches\s+to\b", re.I),
        re.compile(r"\bhow\s+does\b.+\bwork\b", re.I),
        re.compile(r"\bdefinition\s+(of\b)?", re.I),
    ]),
    (QueryPattern.BROAD_SURVEY, [
        re.compile(r"\bwhat\s+do\s+sources\s+say\b", re.I),
        re.compile(r"\bstate\s+of\s+(the\s+)?(art|literature|research|field)\b", re.I),
        re.compile(r"\boverview\s+of\b", re.I),
        re.compile(r"\bsummarize\b", re.I),
    ]),
]


def classify_query(query: str) -> QueryPattern:
    """Classify *query* into a retrieval pattern. First match wins."""
    for pattern, regexes in _PATTERN_RULES:
        for rx in regexes:
            if rx.search(query):
                return pattern
    return QueryPattern.DEFAULT


# ---------------------------------------------------------------------------
# Entity pre-flight search helpers (Task 2)
# ---------------------------------------------------------------------------

@dataclass
class EntityMatch:
    """A knowledge-graph entity matched during pre-flight search."""
    name: str
    entity_type: str
    score: float
    source: str


_QUOTED_RE = re.compile(r"""['""\u2018\u201c](.{3,}?)['""\u2019\u201d]""")
_BIBTEX_KEY_RE = re.compile(r"\b([a-z]+\d{4}[a-z]?)\b")


def extract_query_targets(query: str) -> list[str]:
    """Extract likely entity names from *query*.

    Returns quoted strings and bibtex-key patterns, deduplicated
    (quoted version wins over bibtex duplicate).
    """
    quoted = _QUOTED_RE.findall(query)
    bibtex = _BIBTEX_KEY_RE.findall(query)

    seen: set[str] = set()
    targets: list[str] = []

    # Quoted strings take priority
    for q in quoted:
        low = q.lower()
        if low not in seen:
            seen.add(low)
            targets.append(q)

    # Add bibtex keys not already covered by a quoted string
    for b in bibtex:
        low = b.lower()
        if low not in seen:
            seen.add(low)
            targets.append(b)

    return targets


def _search_entities_in_graph(
    nodes: dict[str, dict], targets: list[str]
) -> list[EntityMatch]:
    """Substring-search *targets* against graph *nodes*.

    Returns matches sorted by score descending, deduplicated by name.
    """
    if not nodes or not targets:
        return []

    seen_names: set[str] = set()
    matches: list[EntityMatch] = []

    for target in targets:
        target_lower = target.lower()
        for node_name, node_data in nodes.items():
            name_lower = node_name.lower()
            if target_lower not in name_lower:
                continue
            if name_lower in seen_names:
                continue
            seen_names.add(name_lower)
            # Exact match -> 1.0, otherwise ratio of target length to node name length
            if target_lower == name_lower:
                score = 1.0
            else:
                score = round(len(target_lower) / len(name_lower), 4)
            matches.append(
                EntityMatch(
                    name=node_name,
                    entity_type=node_data.get("entity_type", "unknown"),
                    score=score,
                    source="graph",
                )
            )

    matches.sort(key=lambda m: m.score, reverse=True)
    return matches


def _get_graph_nodes() -> dict[str, dict]:
    """Load all graph nodes from the GraphML file.

    Returns ``{name: {entity_type, ...}}`` or empty dict if unavailable.
    """
    try:
        import networkx as nx
    except ImportError:
        return {}

    graph_path = Path(WORKING_DIR) / "graph_chunk_entity_relation.graphml"
    if not graph_path.exists():
        return {}

    G = nx.read_graphml(str(graph_path))
    result: dict[str, dict] = {}
    for node, data in G.nodes(data=True):
        result[node] = dict(data)
    return result


def _get_entity_relationships(
    nodes_dict: dict[str, dict], entity_names: list[str]
) -> list[str]:
    """Get direct relationships for *entity_names* from GraphML.

    Returns formatted strings like ``"A → relates_to → B"``, deduplicated.
    """
    try:
        import networkx as nx
    except ImportError:
        return []

    graph_path = Path(WORKING_DIR) / "graph_chunk_entity_relation.graphml"
    if not graph_path.exists():
        return []

    G = nx.read_graphml(str(graph_path))

    # Build a case-insensitive lookup from graph names to canonical names
    name_lookup: dict[str, str] = {n.lower(): n for n in G.nodes()}

    seen: set[str] = set()
    results: list[str] = []

    for name in entity_names:
        canonical = name_lookup.get(name.lower())
        if canonical is None:
            continue

        # Outgoing edges
        for _src, tgt, data in G.edges(canonical, data=True):
            rel = data.get("relationship") or data.get("label", "related_to")
            entry = f"{canonical} \u2192 {rel} \u2192 {tgt}"
            if entry not in seen:
                seen.add(entry)
                results.append(entry)

        # Incoming edges (DiGraph)
        if hasattr(G, "in_edges"):
            for src, _tgt, data in G.in_edges(canonical, data=True):
                rel = data.get("relationship") or data.get("label", "related_to")
                entry = f"{src} \u2192 {rel} \u2192 {canonical}"
                if entry not in seen:
                    seen.add(entry)
                    results.append(entry)

    return results


# --- Multi-strategy retrieval ---

_PATTERN_MODES: dict[QueryPattern, list[str]] = {
    QueryPattern.SPECIFIC_PAPER: ["naive", "local"],
    QueryPattern.CONCEPT_EXPLORATION: ["hybrid", "naive"],
    QueryPattern.EVIDENCE: ["hybrid", "naive"],
    QueryPattern.CONTRADICTION: ["global", "hybrid"],
    QueryPattern.BROAD_SURVEY: ["hybrid", "naive"],
    QueryPattern.DEFAULT: ["hybrid", "naive"],
}

_DEFAULT_MODES: list[str] = ["hybrid", "naive"]


def get_retrieval_modes(pattern: QueryPattern) -> list[str]:
    """Return the LightRAG retrieval modes for a query pattern."""
    return _PATTERN_MODES.get(pattern, _DEFAULT_MODES)


def merge_retrieval_results(results: list[dict]) -> dict:
    """Merge multiple raw retrieval data dicts, deduplicating entries.

    Entities are deduplicated by ``entity_name``, relationships by
    ``(src_id, tgt_id)`` tuple, and chunks by ``content`` string.
    First occurrence wins in all cases.
    """
    entities: list[dict] = []
    relationships: list[dict] = []
    chunks: list[dict] = []
    seen_entities: set[str] = set()
    seen_rels: set[tuple[str, str]] = set()
    seen_chunks: set[str] = set()

    for data in results:
        for ent in data.get("entities", []):
            name = ent.get("entity_name", "")
            if name not in seen_entities:
                seen_entities.add(name)
                entities.append(ent)

        for rel in data.get("relationships", []):
            key = (rel.get("src_id", ""), rel.get("tgt_id", ""))
            if key not in seen_rels:
                seen_rels.add(key)
                relationships.append(rel)

        for chunk in data.get("chunks", []):
            content = chunk.get("content", "")
            if content not in seen_chunks:
                seen_chunks.add(content)
                chunks.append(chunk)

    return {"entities": entities, "relationships": relationships, "chunks": chunks}


async def _multi_retrieve(rag, query: str, pattern: QueryPattern) -> dict:
    """Run retrieval across multiple modes concurrently and merge results."""
    from lightrag import QueryParam

    modes = get_retrieval_modes(pattern)

    async def _fetch(mode: str) -> dict | None:
        try:
            resp = await rag.aquery_data(query, QueryParam(mode=mode))
            if isinstance(resp, dict) and resp.get("status") == "success":
                return resp.get("data", {})
        except Exception:
            pass
        return None

    raw = await asyncio.gather(*[_fetch(m) for m in modes])
    successful = [r for r in raw if r is not None]
    return merge_retrieval_results(successful)


async def _cached_query(rag, query: str, mode: str) -> str:
    """Query with file-based caching. Returns cached result if available."""
    from lightrag import QueryParam

    cache_path = _get_cache_path(query, mode)
    if cache_path.exists():
        print("(using cached result)", file=sys.stderr)
        return cache_path.read_text(encoding="utf-8")

    query_model = _get_query_model_func()
    result = await rag.aquery(query, param=QueryParam(mode=mode, model_func=query_model))
    os.makedirs(CACHE_DIR, exist_ok=True)
    cache_path.write_text(str(result), encoding="utf-8")
    return result


# ---------------------------------------------------------------------------
# LightRAG initialization
# ---------------------------------------------------------------------------


def _get_namespace():
    """Read knowledge_namespace from .paper.json for OpenSearch index isolation."""
    paper_json = Path(".paper.json")
    if paper_json.exists():
        import json
        config = json.loads(paper_json.read_text(encoding="utf-8"))
        ns = config.get("knowledge_namespace")
        if ns:
            return ns
    # Fallback: hash of cwd for projects without the field
    import hashlib
    return hashlib.sha256(os.getcwd().encode()).hexdigest()[:16]


def create_rag():
    """Create and return a LightRAG instance configured for OpenRouter."""
    from lightrag import LightRAG
    from lightrag.llm.openai import openai_complete, openai_embed

    api_key = get_api_key()

    try:
        from lightrag.utils import EmbeddingFunc
    except ImportError:
        from lightrag.base import EmbeddingFunc

    addon_params = {"language": SUMMARY_LANGUAGE}
    if ENTITY_TYPES is not None:
        addon_params["entity_types"] = ENTITY_TYPES

    kwargs = dict(
        working_dir=WORKING_DIR,
        # LLM
        llm_model_func=openai_complete,
        llm_model_name=LLM_MODEL,
        llm_model_kwargs={
            "base_url": OPENROUTER_BASE_URL,
            "api_key": api_key,
        },
        llm_model_max_async=LLM_MAX_ASYNC,
        default_llm_timeout=LLM_TIMEOUT,
        enable_llm_cache=ENABLE_LLM_CACHE,
        enable_llm_cache_for_entity_extract=ENABLE_LLM_CACHE_FOR_EXTRACT,
        # Embedding
        embedding_func=EmbeddingFunc(
            embedding_dim=EMBEDDING_DIM,
            max_token_size=EMBEDDING_LENGTH,
            func=partial(
                openai_embed.func,
                model=EMBEDDING_MODEL,
                base_url=OPENROUTER_BASE_URL,
                api_key=api_key,
            ),
        ),
        embedding_batch_num=EMBEDDING_BATCH_NUM,
        embedding_func_max_async=EMBEDDING_FUNC_MAX_ASYNC,
        default_embedding_timeout=EMBEDDING_TIMEOUT,
        embedding_cache_config={
            "enabled": EMBEDDING_CACHE_ENABLED,
            "similarity_threshold": EMBEDDING_CACHE_SIMILARITY,
            "use_llm_check": False,
        },
        # Chunking
        chunk_token_size=CHUNK_TOKEN_SIZE,
        chunk_overlap_token_size=CHUNK_OVERLAP_TOKEN_SIZE,
        tiktoken_model_name=TIKTOKEN_MODEL_NAME,
        # Entity extraction
        entity_extract_max_gleaning=ENTITY_EXTRACT_MAX_GLEANING,
        max_extract_input_tokens=MAX_EXTRACT_INPUT_TOKENS,
        force_llm_summary_on_merge=FORCE_LLM_SUMMARY_ON_MERGE,
        # Summary
        summary_max_tokens=SUMMARY_MAX_TOKENS,
        summary_context_size=SUMMARY_CONTEXT_SIZE,
        summary_length_recommended=SUMMARY_LENGTH_RECOMMENDED,
        # Query/retrieval defaults
        top_k=TOP_K,
        chunk_top_k=CHUNK_TOP_K,
        max_entity_tokens=MAX_ENTITY_TOKENS,
        max_relation_tokens=MAX_RELATION_TOKENS,
        max_total_tokens=MAX_TOTAL_TOKENS,
        cosine_better_than_threshold=COSINE_THRESHOLD,
        related_chunk_number=RELATED_CHUNK_NUMBER,
        kg_chunk_pick_method=KG_CHUNK_PICK_METHOD,
        # Graph limits
        max_parallel_insert=MAX_PARALLEL_INSERT,
        max_graph_nodes=MAX_GRAPH_NODES,
        max_source_ids_per_entity=MAX_SOURCE_IDS_PER_ENTITY,
        max_source_ids_per_relation=MAX_SOURCE_IDS_PER_RELATION,
        source_ids_limit_method=SOURCE_IDS_LIMIT_METHOD,
        max_file_paths=MAX_FILE_PATHS,
        # Addon
        addon_params=addon_params,
    )

    if LIGHTRAG_STORAGE == "opensearch":
        namespace = _get_namespace()
        # Set OpenSearch defaults if not explicitly configured.
        # LightRAG requires OPENSEARCH_HOSTS even though it defaults to localhost:9200.
        os.environ.setdefault("OPENSEARCH_HOSTS", "localhost:9200")
        os.environ.setdefault("OPENSEARCH_USER", "admin")
        os.environ.setdefault("OPENSEARCH_PASSWORD", "ResearchAgent1!")
        os.environ.setdefault("OPENSEARCH_USE_SSL", "false")
        kwargs.update(
            workspace=namespace,
            kv_storage="OpenSearchKVStorage",
            vector_storage="OpenSearchVectorDBStorage",
            graph_storage="OpenSearchGraphStorage",
            doc_status_storage="OpenSearchDocStatusStorage",
        )
        print(f"Using OpenSearch backend (namespace: {namespace})", file=sys.stderr)

    rag = LightRAG(**kwargs)
    return rag


async def _init_rag():
    """Create, initialize, and return a ready-to-use LightRAG instance."""
    rag = create_rag()
    await rag.initialize_storages()
    from lightrag.kg.shared_storage import initialize_pipeline_status
    await initialize_pipeline_status()
    return rag


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def extract_pdf_text(pdf_path: Path) -> str:
    """Extract full text from a PDF using pymupdf."""
    try:
        import fitz  # pymupdf
    except ImportError:
        print(
            f"Warning: pymupdf not installed, skipping PDF {pdf_path.name}. "
            "Install with: pip install pymupdf",
            file=sys.stderr,
        )
        return ""

    try:
        doc = fitz.open(str(pdf_path))
        pages = []
        for page in doc:
            text = page.get_text()
            if text.strip():
                pages.append(text)
        doc.close()
        full_text = "\n\n".join(pages)
        if not full_text.strip():
            return ""
        # Prepend a header so the graph can attribute entities back to this PDF
        return f"# PDF: {pdf_path.stem}\n\nSource file: {pdf_path.name}\n\n{full_text}"
    except Exception as e:
        print(f"Warning: Failed to extract text from {pdf_path.name}: {e}", file=sys.stderr)
        return ""


async def cmd_build(_args):
    """Build or update the knowledge graph from source extracts and PDFs."""
    if not check_api_key_available():
        _graceful_exit_no_api_key("build")
    sources_path = Path(SOURCES_DIR)
    attachments_path = Path(ATTACHMENTS_DIR)

    documents = []
    ids = []

    # --- Source extract markdown files ---
    if sources_path.exists():
        source_files = sorted(sources_path.glob("*.md"))
        for f in source_files:
            content = f.read_text(encoding="utf-8")
            documents.append(content)
            ids.append(f.stem)
        print(f"Found {len(source_files)} source extracts in {SOURCES_DIR}/")
    else:
        source_files = []
        print(f"Warning: {SOURCES_DIR}/ not found, skipping source extracts.", file=sys.stderr)

    # --- Prepared documents (claims, methodology, assumptions) ---
    # Generated by reviewer-kb.py prepare into research/prepared/**/*.md.
    # Silently skipped when the directory does not exist.
    prepared_path = Path(PREPARED_DIR)
    prepared_count = 0
    if prepared_path.exists():
        prepared_files = sorted(prepared_path.rglob("*.md"))
        for f in prepared_files:
            content = f.read_text(encoding="utf-8")
            if content.strip():
                # Use relative path from prepared/ as the document ID to avoid
                # collisions with source extract IDs.
                # e.g. "prepared_claims_C3" or "prepared_methodology_scf-overlap"
                rel_path = f.relative_to(prepared_path)
                doc_id = f"prepared_{rel_path.with_suffix('').as_posix().replace('/', '_')}"
                documents.append(content)
                ids.append(doc_id)
                prepared_count += 1
        if prepared_files:
            print(f"Found {prepared_count} prepared documents in {PREPARED_DIR}/")

    # --- Parsed markdown or PDF files in attachments ---
    # Prefer Docling-parsed markdown (attachments/parsed/<key>.md) over raw PDF
    # extraction. This avoids duplicate ingestion and gives higher quality text.
    parsed_path = Path(PARSED_DIR)
    pdf_count = 0
    parsed_count = 0
    parsed_stems = set()

    if parsed_path.exists():
        parsed_files = sorted(parsed_path.glob("*.md"))
        for f in parsed_files:
            content = f.read_text(encoding="utf-8")
            if content.strip():
                doc_id = f"parsed_{f.stem}"
                documents.append(content)
                ids.append(doc_id)
                parsed_count += 1
                parsed_stems.add(f.stem)
        if parsed_files:
            print(f"Found {parsed_count} Docling-parsed files in {PARSED_DIR}/")

    if attachments_path.exists():
        pdf_files = sorted(attachments_path.glob("*.pdf"))
        for pdf in pdf_files:
            if pdf.stem in parsed_stems:
                continue  # Already ingested via parsed markdown
            text = extract_pdf_text(pdf)
            if text:
                doc_id = f"pdf_{pdf.stem}"
                documents.append(text)
                ids.append(doc_id)
                pdf_count += 1
        if pdf_files:
            skipped = len([p for p in pdf_files if p.stem in parsed_stems])
            print(f"Extracted text from {pdf_count}/{len(pdf_files)} PDFs in {ATTACHMENTS_DIR}/ ({skipped} skipped — parsed markdown exists)")
    else:
        print(f"No {ATTACHMENTS_DIR}/ directory found, skipping PDFs.")

    if not documents:
        print("Error: No documents to ingest (no source extracts and no readable PDFs).", file=sys.stderr)
        sys.exit(1)

    print(f"Building knowledge graph from {len(documents)} total documents...")

    os.makedirs(WORKING_DIR, exist_ok=True)
    rag = await _init_rag()
    await rag.ainsert(documents, ids=ids, file_paths=ids)

    entity_count = 0
    relation_count = 0
    if LIGHTRAG_STORAGE == "opensearch":
        try:
            graph = rag.chunk_entity_relation_graph
            all_nodes = await graph.get_all_nodes()
            all_edges = await graph.get_all_edges()
            entity_count = len(all_nodes) if all_nodes else 0
            relation_count = len(all_edges) if all_edges else 0
        except Exception:
            pass
    else:
        try:
            import networkx as nx
            graph_path = Path(WORKING_DIR) / "graph_chunk_entity_relation.graphml"
            if graph_path.exists():
                G = nx.read_graphml(str(graph_path))
                entity_count = G.number_of_nodes()
                relation_count = G.number_of_edges()
        except Exception:
            pass

    summary = (
        f"Built knowledge graph: {entity_count} entities, "
        f"{relation_count} relationships from {len(documents)} documents "
        f"({len(source_files)} source extracts + {prepared_count} prepared + {parsed_count} parsed + {pdf_count} PDFs)"
    )
    print(summary)

    log_operation("Build", {
        "Tool": "scripts/knowledge.py build",
        "Source extracts": f"{len(source_files)} from {SOURCES_DIR}",
        "Prepared documents": f"{prepared_count} from {PREPARED_DIR}",
        "Parsed markdown": f"{parsed_count} from {PARSED_DIR}",
        "PDFs ingested": f"{pdf_count} from {ATTACHMENTS_DIR} (skipped {len(parsed_stems)} with parsed markdown)",
        "Total documents": str(len(documents)),
        "Entities extracted": str(entity_count),
        "Relationships extracted": str(relation_count),
        "Storage": WORKING_DIR,
    })

    _save_build_timestamp()
    _invalidate_cache()


async def cmd_update(_args):
    """Incremental update: only ingest files newer than last build."""
    if not check_api_key_available():
        _graceful_exit_no_api_key("update")
    last_build_path = Path(LAST_BUILD_FILE)
    if not last_build_path.exists():
        print("No previous build found. Running full build instead.")
        await cmd_build(_args)
        return

    last_build_time = datetime.fromisoformat(
        last_build_path.read_text(encoding="utf-8").strip()
    ).timestamp()

    sources_path = Path(SOURCES_DIR)
    attachments_path = Path(ATTACHMENTS_DIR)

    documents = []
    ids = []

    # --- New/changed source extracts ---
    new_sources = 0
    if sources_path.exists():
        for f in sorted(sources_path.glob("*.md")):
            if f.stat().st_mtime > last_build_time:
                documents.append(f.read_text(encoding="utf-8"))
                ids.append(f.stem)
                new_sources += 1

    # --- New/changed prepared documents ---
    # Silently skipped when the directory does not exist.
    prepared_path = Path(PREPARED_DIR)
    new_prepared = 0
    if prepared_path.exists():
        for f in sorted(prepared_path.rglob("*.md")):
            if f.stat().st_mtime > last_build_time:
                content = f.read_text(encoding="utf-8")
                if content.strip():
                    rel_path = f.relative_to(prepared_path)
                    doc_id = f"prepared_{rel_path.with_suffix('').as_posix().replace('/', '_')}"
                    documents.append(content)
                    ids.append(doc_id)
                    new_prepared += 1

    # --- New/changed parsed markdown or PDFs ---
    parsed_path = Path(PARSED_DIR)
    new_parsed = 0
    new_pdfs = 0
    parsed_stems = set()

    if parsed_path.exists():
        for f in sorted(parsed_path.glob("*.md")):
            parsed_stems.add(f.stem)
            if f.stat().st_mtime > last_build_time:
                content = f.read_text(encoding="utf-8")
                if content.strip():
                    documents.append(content)
                    ids.append(f"parsed_{f.stem}")
                    new_parsed += 1

    if attachments_path.exists():
        for pdf in sorted(attachments_path.glob("*.pdf")):
            if pdf.stem in parsed_stems:
                continue  # Already handled via parsed markdown
            if pdf.stat().st_mtime > last_build_time:
                text = extract_pdf_text(pdf)
                if text:
                    documents.append(text)
                    ids.append(f"pdf_{pdf.stem}")
                    new_pdfs += 1

    if not documents:
        print("No new or changed files since last build. Graph is up to date.")
        return

    print(f"Updating knowledge graph with {len(documents)} new/changed documents "
          f"({new_sources} sources + {new_prepared} prepared + {new_parsed} parsed + {new_pdfs} PDFs)...")

    rag = await _init_rag()
    await rag.ainsert(documents, ids=ids, file_paths=ids)

    _save_build_timestamp()
    _invalidate_cache()

    print(f"Updated knowledge graph with {len(documents)} documents.")

    log_operation("Update", {
        "Tool": "scripts/knowledge.py update",
        "New sources": str(new_sources),
        "New prepared": str(new_prepared),
        "New parsed": str(new_parsed),
        "New PDFs": str(new_pdfs),
        "Total new documents": str(len(documents)),
    })


async def cmd_query(args):
    """Freeform semantic search across the knowledge graph."""
    if not check_api_key_available():
        _graceful_exit_no_api_key("query")
    rag = await _init_rag()

    mode = getattr(args, "mode", None) or DEFAULT_QUERY_MODE
    result = await _cached_query(rag, args.question, mode)

    print(f"## Results ({mode} mode)\n\n{result}")

    log_operation("Query", {
        "Tool": "scripts/knowledge.py query",
        "Query": args.question,
        "Mode": mode,
        "Result": "SUCCESS" if result else "EMPTY",
    })


async def cmd_contradictions(_args):
    """Find conflicting claims across source documents."""
    if not check_api_key_available():
        _graceful_exit_no_api_key("contradictions")
    rag = await _init_rag()

    prompt = (
        "Identify contradictions, tensions, and conflicting claims across the source documents "
        "in this knowledge graph. For each contradiction found, report:\n"
        "1. The specific claims that conflict\n"
        "2. Which source documents (by bibtex key) make each claim\n"
        "3. Whether the contradiction is resolved in any source, or remains open\n\n"
        "Focus on substantive intellectual disagreements, not minor differences in framing. "
        "Format each contradiction as a numbered item."
    )

    result = await _cached_query(rag, prompt, "global")

    output = (
        f"# Knowledge Graph — Contradictions Report\n\n"
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}\n\n"
        f"{result}"
    )
    print(output)

    Path(CONTRADICTIONS_FILE).write_text(output, encoding="utf-8")
    print(f"\nSaved to {CONTRADICTIONS_FILE}")

    log_operation("Contradictions", {
        "Tool": "scripts/knowledge.py contradictions",
        "Mode": "global",
        "Result": f"Report written to {CONTRADICTIONS_FILE}",
    })


async def cmd_evidence_for(args):
    """Find sources supporting a specific claim."""
    if not check_api_key_available():
        _graceful_exit_no_api_key("evidence-for")
    rag = await _init_rag()

    prompt = (
        f"Find all evidence in the source documents that SUPPORTS the following claim:\n\n"
        f"\"{args.claim}\"\n\n"
        f"For each piece of evidence, report:\n"
        f"1. The specific finding or data point\n"
        f"2. Which source document (by bibtex key) it comes from\n"
        f"3. How strongly it supports the claim (direct evidence vs. tangential)\n\n"
        f"Only include evidence that genuinely supports the claim. "
        f"Do not stretch or misrepresent findings."
    )

    result = await _cached_query(rag, prompt, "hybrid")
    print(f"## Evidence Supporting: \"{args.claim}\"\n\n{result}")

    log_operation("Evidence-For", {
        "Tool": "scripts/knowledge.py evidence-for",
        "Query": args.claim,
        "Mode": "hybrid",
        "Result": "SUCCESS" if result else "EMPTY",
    })


async def cmd_evidence_against(args):
    """Find sources challenging a specific claim."""
    if not check_api_key_available():
        _graceful_exit_no_api_key("evidence-against")
    rag = await _init_rag()

    prompt = (
        f"Find all evidence in the source documents that CONTRADICTS or CHALLENGES "
        f"the following claim:\n\n"
        f"\"{args.claim}\"\n\n"
        f"For each piece of evidence, report:\n"
        f"1. The specific finding or data point that conflicts\n"
        f"2. Which source document (by bibtex key) it comes from\n"
        f"3. How strongly it undermines the claim\n\n"
        f"Include alternative explanations, methodological critiques, and null findings. "
        f"Be thorough — a reviewer would use this to attack the claim."
    )

    result = await _cached_query(rag, prompt, "hybrid")
    print(f"## Evidence Against: \"{args.claim}\"\n\n{result}")

    log_operation("Evidence-Against", {
        "Tool": "scripts/knowledge.py evidence-against",
        "Query": args.claim,
        "Mode": "hybrid",
        "Result": "SUCCESS" if result else "EMPTY",
    })


async def cmd_entities(_args):
    """List all extracted entities from the knowledge graph."""
    if LIGHTRAG_STORAGE == "opensearch":
        if not check_api_key_available():
            _graceful_exit_no_api_key("entities")
        rag = await _init_rag()

        graph = rag.chunk_entity_relation_graph
        all_nodes = await graph.get_all_nodes()
        entities = {}
        for node in all_nodes:
            data = await graph.get_node(node)
            entity_type = (data or {}).get("entity_type", "unknown")
            entities.setdefault(entity_type, []).append(node)

        total = sum(len(v) for v in entities.values())
        print(f"## Entities ({total} total)\n")
        for entity_type, names in sorted(entities.items()):
            print(f"### {entity_type} ({len(names)})")
            for name in sorted(names):
                print(f"- {name}")
            print()

        log_operation("Entities", {
            "Tool": "scripts/knowledge.py entities",
            "Result": f"{total} entities across {len(entities)} types",
        })
        return

    # File-based: read GraphML directly
    import networkx as nx

    graph_path = Path(WORKING_DIR) / "graph_chunk_entity_relation.graphml"
    if not graph_path.exists():
        print("Error: Knowledge graph not built yet. Run 'build' first.", file=sys.stderr)
        sys.exit(1)

    G = nx.read_graphml(str(graph_path))

    entities = {}
    for node, data in G.nodes(data=True):
        entity_type = data.get("entity_type", "unknown")
        if entity_type not in entities:
            entities[entity_type] = []
        entities[entity_type].append(node)

    print(f"## Entities ({G.number_of_nodes()} total)\n")
    for entity_type, names in sorted(entities.items()):
        print(f"### {entity_type} ({len(names)})")
        for name in sorted(names):
            print(f"- {name}")
        print()

    log_operation("Entities", {
        "Tool": "scripts/knowledge.py entities",
        "Result": f"{G.number_of_nodes()} entities across {len(entities)} types",
    })


async def cmd_relationships(args):
    """Show how a specific entity connects to others in the graph."""
    if LIGHTRAG_STORAGE == "opensearch":
        if not check_api_key_available():
            _graceful_exit_no_api_key("relationships")
        rag = await _init_rag()

        graph = rag.chunk_entity_relation_graph
        all_nodes = await graph.get_all_nodes()
        target = args.entity.lower()
        matches = [n for n in all_nodes if target in n.lower()]

        if not matches:
            print(f"No entity matching '{args.entity}' found in the graph.", file=sys.stderr)
            print("Try 'entities' command to see all available entities.", file=sys.stderr)
            sys.exit(1)

        for match in matches:
            print(f"## Relationships for: {match}\n")
            edges = await graph.get_node_edges(match)
            if edges:
                for edge in edges:
                    src, tgt = edge[0], edge[1]
                    data = edge[2] if len(edge) > 2 else {}
                    other = tgt if src == match else src
                    rel = data.get("relationship", data.get("label", "related_to"))
                    print(f"  -- {rel} -- {other}")
            print()

        log_operation("Relationships", {
            "Tool": "scripts/knowledge.py relationships",
            "Query": args.entity,
            "Result": f"Found {len(matches)} matching entities",
        })
        return

    # File-based: read GraphML directly
    import networkx as nx

    graph_path = Path(WORKING_DIR) / "graph_chunk_entity_relation.graphml"
    if not graph_path.exists():
        print("Error: Knowledge graph not built yet. Run 'build' first.", file=sys.stderr)
        sys.exit(1)

    G = nx.read_graphml(str(graph_path))

    target = args.entity.lower()
    matches = [n for n in G.nodes() if target in n.lower()]

    if not matches:
        print(f"No entity matching '{args.entity}' found in the graph.", file=sys.stderr)
        print("Try 'entities' command to see all available entities.", file=sys.stderr)
        sys.exit(1)

    for match in matches:
        print(f"## Relationships for: {match}\n")
        for neighbor in G.neighbors(match):
            data = G.edges[match, neighbor]
            rel_type = data.get("relationship", data.get("label", "related_to"))
            print(f"  -- {rel_type} -- {neighbor}")
        print()

    log_operation("Relationships", {
        "Tool": "scripts/knowledge.py relationships",
        "Query": args.entity,
        "Result": f"Found {len(matches)} matching entities",
    })


async def cmd_coverage(args):
    """Check which graph entities appear in a document."""
    doc_path = Path(args.document)
    if not doc_path.exists():
        print(f"Error: Document not found: {args.document}", file=sys.stderr)
        sys.exit(1)
    doc_text = doc_path.read_text(encoding="utf-8").lower()

    if LIGHTRAG_STORAGE == "opensearch":
        if not check_api_key_available():
            _graceful_exit_no_api_key("coverage")
        rag = await _init_rag()

        graph = rag.chunk_entity_relation_graph
        all_nodes = await graph.get_all_nodes()

        missing = []
        present = []
        for node in all_nodes:
            edges = await graph.get_node_edges(node)
            degree = len(edges) if edges else 0
            if node.lower() in doc_text:
                present.append((node, degree))
            else:
                missing.append((node, degree))

        missing.sort(key=lambda x: x[1], reverse=True)
        total = len(present) + len(missing)
        print(f"## Entity Coverage for {args.document}\n")
        print(f"**Present**: {len(present)}/{total} entities found in document\n")
        if missing:
            print(f"### Missing Entities ({len(missing)}) — sorted by importance\n")
            for name, degree in missing:
                print(f"- **{name}** ({degree} connections)")
        else:
            print("All entities are covered in the document.")

        log_operation("Coverage", {
            "Tool": "scripts/knowledge.py coverage",
            "Document": args.document,
            "Present": str(len(present)),
            "Missing": str(len(missing)),
            "Total": str(total),
        })
        return

    # File-based: read GraphML directly
    import networkx as nx

    graph_path = Path(WORKING_DIR) / "graph_chunk_entity_relation.graphml"
    if not graph_path.exists():
        print("Error: Knowledge graph not built yet. Run 'build' first.", file=sys.stderr)
        sys.exit(1)

    G = nx.read_graphml(str(graph_path))

    # Build entity list with connection counts
    missing = []
    present = []
    for node in G.nodes():
        degree = G.degree(node)
        if node.lower() in doc_text:
            present.append((node, degree))
        else:
            missing.append((node, degree))

    # Sort missing by degree (most connected first = most important)
    missing.sort(key=lambda x: x[1], reverse=True)

    total = len(present) + len(missing)
    print(f"## Entity Coverage for {args.document}\n")
    print(f"**Present**: {len(present)}/{total} entities found in document\n")

    if missing:
        print(f"### Missing Entities ({len(missing)}) — sorted by importance\n")
        for name, degree in missing:
            print(f"- **{name}** ({degree} connections)")
    else:
        print("All entities are covered in the document.")

    log_operation("Coverage", {
        "Tool": "scripts/knowledge.py coverage",
        "Document": args.document,
        "Present": str(len(present)),
        "Missing": str(len(missing)),
        "Total": str(total),
    })


# ---------------------------------------------------------------------------
# Queue-based ingestion
# ---------------------------------------------------------------------------


def _classify_file(path):
    """Determine (doc_id, priority) for a file. Priority: 1=source, 2=prepared, 3=parsed, 4=pdf."""
    try:
        rel = str(path.relative_to(Path.cwd().resolve()))
    except ValueError:
        rel = str(path)

    if rel.startswith(SOURCES_DIR + "/"):
        return path.stem, 1
    if rel.startswith(PREPARED_DIR + "/"):
        try:
            rel_path = path.relative_to(Path.cwd() / PREPARED_DIR)
        except ValueError:
            rel_path = Path(path.name)
        return f"prepared_{rel_path.with_suffix('').as_posix().replace('/', '_')}", 2
    if rel.startswith(PARSED_DIR + "/"):
        return f"parsed_{path.stem}", 3
    if path.suffix == ".pdf":
        return f"pdf_{path.stem}", 4
    return path.stem, 2


def _is_worker_alive():
    """Check if a worker process is running. Returns (alive, pid)."""
    pid_path = Path(WORKER_PID_FILE)
    if not pid_path.exists():
        return False, None
    try:
        pid = int(pid_path.read_text(encoding="utf-8").strip())
        os.kill(pid, 0)
        return True, pid
    except (ValueError, ProcessLookupError, PermissionError, OSError):
        pid_path.unlink(missing_ok=True)
        return False, None


def _read_queue():
    """Read all items from the queue file."""
    queue_path = Path(QUEUE_FILE)
    if not queue_path.exists():
        return []
    items = []
    for line in queue_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            try:
                items.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    return items


def _read_progress():
    """Read progress tracking."""
    progress_path = Path(PROGRESS_FILE)
    if not progress_path.exists():
        return {"processed": {}}
    try:
        return json.loads(progress_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {"processed": {}}


def _save_progress(progress):
    """Save progress tracking atomically via temp file + rename."""
    import tempfile

    progress_path = Path(PROGRESS_FILE)
    fd, tmp = tempfile.mkstemp(dir=WORKING_DIR, suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            json.dump(progress, f, indent=2)
        os.replace(tmp, str(progress_path))
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def _log_worker(message):
    """Append a timestamped message to the worker log."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    with open(WORKER_LOG_FILE, "a") as f:
        f.write(f"[{timestamp}] {message}\n")
    print(f"[{timestamp}] {message}", file=sys.stderr)


def _read_file_content(path):
    """Read content from a file, handling PDFs via pymupdf extraction."""
    if path.suffix == ".pdf":
        return extract_pdf_text(path)
    return path.read_text(encoding="utf-8")


async def cmd_serve(_args):
    """Long-running worker that processes the ingestion queue."""
    if not check_api_key_available():
        _graceful_exit_no_api_key("serve")
    os.makedirs(WORKING_DIR, exist_ok=True)

    # Atomically create PID file to prevent duplicate workers
    try:
        fd = os.open(WORKER_PID_FILE, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
        os.write(fd, str(os.getpid()).encode())
        os.close(fd)
    except FileExistsError:
        alive, old_pid = _is_worker_alive()
        if alive:
            print(f"Worker already running (PID {old_pid})", file=sys.stderr)
            sys.exit(1)
        # Stale PID file from a crashed worker — reclaim it
        Path(WORKER_PID_FILE).write_text(str(os.getpid()), encoding="utf-8")

    shutdown_event = asyncio.Event()
    loop = asyncio.get_running_loop()
    loop.add_signal_handler(signal.SIGTERM, shutdown_event.set)
    loop.add_signal_handler(signal.SIGINT, shutdown_event.set)

    _log_worker(f"Worker starting (PID {os.getpid()})")

    ingested_count = 0
    try:
        rag = await _init_rag()
        _log_worker("RAG initialized, waiting for queue items")

        progress = _read_progress()

        while not shutdown_event.is_set():
            # Deduplicate queue: last enqueue for each doc_id wins
            items = _read_queue()
            unique = {}
            for item in items:
                unique[item["doc_id"]] = item

            pending = [
                item for item in unique.values()
                if item["doc_id"] not in progress["processed"]
            ]

            if not pending:
                try:
                    await asyncio.wait_for(shutdown_event.wait(), timeout=WORKER_POLL_INTERVAL)
                    break  # shutdown signal
                except asyncio.TimeoutError:
                    continue  # poll again

            # Process highest-priority items first (small sources before big PDFs)
            pending.sort(key=lambda x: x.get("priority", 99))

            # --- Pre-read phase: build batch, skipping missing/empty files ---
            batch_docs = []
            batch_ids = []
            for item in pending[:WORKER_BATCH_SIZE]:
                doc_id = item["doc_id"]
                file_path = Path(item["path"])

                if not file_path.exists():
                    _log_worker(f"SKIP (missing): {doc_id}")
                    progress["processed"][doc_id] = {
                        "status": "skipped",
                        "reason": "file_not_found",
                        "completed_at": datetime.now(timezone.utc).isoformat(),
                    }
                    continue

                content = _read_file_content(file_path)
                if not content or not content.strip():
                    _log_worker(f"SKIP (empty): {doc_id}")
                    progress["processed"][doc_id] = {
                        "status": "skipped",
                        "reason": "empty_file",
                        "completed_at": datetime.now(timezone.utc).isoformat(),
                    }
                    continue

                batch_docs.append(content)
                batch_ids.append(doc_id)

            # Persist any skip decisions before the potentially long ingest
            _save_progress(progress)

            if not batch_docs:
                continue

            # --- Ingest phase: single ainsert() for the whole batch ---
            _log_worker(f"BATCH INGEST: {len(batch_docs)} docs ({', '.join(batch_ids[:5])}{'...' if len(batch_ids) > 5 else ''})")
            try:
                await rag.ainsert(batch_docs, ids=batch_ids, file_paths=batch_ids)
                now = datetime.now(timezone.utc).isoformat()
                for doc_id, content in zip(batch_ids, batch_docs):
                    ingested_count += 1
                    progress["processed"][doc_id] = {
                        "status": "done",
                        "chars": len(content),
                        "completed_at": now,
                    }
                _log_worker(f"OK: batch of {len(batch_ids)} docs")
                _save_build_timestamp()
                _invalidate_cache()
            except Exception as e:
                # On batch failure, mark all docs in the batch as failed.
                # A future enhancement could retry individually.
                _log_worker(f"FAIL (batch): {e}")
                now = datetime.now(timezone.utc).isoformat()
                for doc_id in batch_ids:
                    progress["processed"][doc_id] = {
                        "status": "failed",
                        "error": str(e),
                        "completed_at": now,
                    }

            _save_progress(progress)

    finally:
        Path(WORKER_PID_FILE).unlink(missing_ok=True)
        if ingested_count > 0:
            _save_build_timestamp()
            _invalidate_cache()
        _log_worker(f"Worker stopped ({ingested_count} documents ingested)")


async def cmd_enqueue(args):
    """Add files to the ingestion queue. Instant, non-blocking."""
    if not check_api_key_available():
        _graceful_exit_no_api_key("enqueue")
    os.makedirs(WORKING_DIR, exist_ok=True)

    progress = _read_progress()
    progress_modified = False
    queue_path = Path(QUEUE_FILE)

    added = 0
    requeued = 0
    skipped = 0

    with open(queue_path, "a") as f:
        for path_str in args.files:
            path = Path(path_str).resolve()
            if not path.exists():
                print(f"Warning: {path_str} not found, skipping", file=sys.stderr)
                continue

            doc_id, priority = _classify_file(path)

            # Check if already processed
            if doc_id in progress["processed"]:
                prev = progress["processed"][doc_id]
                if not getattr(args, "reindex", False) and prev.get("status") == "done":
                    # Skip if file hasn't been modified since last ingest
                    completed_ts = datetime.fromisoformat(
                        prev["completed_at"]
                    ).timestamp()
                    if path.stat().st_mtime <= completed_ts:
                        skipped += 1
                        continue
                # File modified or --reindex: clear progress for re-processing
                del progress["processed"][doc_id]
                progress_modified = True
                requeued += 1

            entry = {
                "path": str(path),
                "doc_id": doc_id,
                "priority": priority,
                "enqueued_at": datetime.now(timezone.utc).isoformat(),
            }
            f.write(json.dumps(entry) + "\n")
            added += 1

    if progress_modified:
        _save_progress(progress)

    parts = []
    if added:
        parts.append(f"{added} queued")
    if requeued:
        parts.append(f"{requeued} re-queued")
    if skipped:
        parts.append(f"{skipped} up-to-date")
    print(", ".join(parts) if parts else "No files to queue")


async def cmd_queue_status(_args):
    """Show ingestion queue status."""
    items = _read_queue()
    progress = _read_progress()

    # Deduplicate by doc_id
    unique = {}
    for item in items:
        unique[item["doc_id"]] = item

    done = failed = skipped_count = 0
    for doc_id in unique:
        info = progress["processed"].get(doc_id)
        if not info:
            continue
        s = info["status"]
        if s == "done":
            done += 1
        elif s == "failed":
            failed += 1
        elif s == "skipped":
            skipped_count += 1

    pending = len(unique) - done - failed - skipped_count
    alive, pid = _is_worker_alive()

    worker_str = f"running (PID {pid})" if alive else "stopped"
    print(f"Worker: {worker_str}")
    print(
        f"Queue:  {pending} pending, {done} done, "
        f"{failed} failed, {skipped_count} skipped ({len(unique)} total)"
    )

    if failed > 0:
        print("\nFailed:")
        for doc_id, info in progress["processed"].items():
            if info.get("status") == "failed":
                print(f"  {doc_id}: {info.get('error', 'unknown')}")


async def cmd_drain(args):
    """Block until the ingestion queue is fully processed."""
    timeout = getattr(args, "timeout", 0)
    start = datetime.now(timezone.utc)

    alive, _ = _is_worker_alive()
    if not alive:
        print("Error: No worker running. Start one with 'serve'.", file=sys.stderr)
        sys.exit(1)

    while True:
        items = _read_queue()
        progress = _read_progress()

        unique = {}
        for item in items:
            unique[item["doc_id"]] = item

        pending = sum(1 for d in unique if d not in progress["processed"])

        if pending == 0:
            print("Queue drained — all items processed.")
            return

        if timeout > 0:
            elapsed = (datetime.now(timezone.utc) - start).total_seconds()
            if elapsed >= timeout:
                print(f"Timed out after {timeout}s with {pending} items pending.")
                sys.exit(1)

        alive, _ = _is_worker_alive()
        if not alive:
            print(f"Worker died with {pending} items pending.", file=sys.stderr)
            sys.exit(1)

        await asyncio.sleep(DRAIN_POLL_INTERVAL)


async def cmd_stop(_args):
    """Gracefully stop the ingestion worker."""
    alive, pid = _is_worker_alive()
    if not alive:
        print("No worker running.")
        return

    os.kill(pid, signal.SIGTERM)
    print(f"Sent SIGTERM to worker (PID {pid})")

    for _ in range(WORKER_STOP_TIMEOUT):
        await asyncio.sleep(1)
        alive, _ = _is_worker_alive()
        if not alive:
            print("Worker stopped.")
            return

    print(f"Worker did not stop within {WORKER_STOP_TIMEOUT}s.", file=sys.stderr)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Knowledge graph for research paper source extracts"
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("build", help="Build/update graph from research/sources/")
    subparsers.add_parser("update", help="Incremental update (new/changed files only)")

    p_query = subparsers.add_parser("query", help="Freeform semantic search")
    p_query.add_argument("question", help="Question to search for")
    p_query.add_argument("--mode", choices=["local", "global", "hybrid", "naive", "mix"],
                         default=None, help=f"Query mode (default: {DEFAULT_QUERY_MODE})")

    subparsers.add_parser("contradictions", help="Find conflicting claims across sources")

    p_efor = subparsers.add_parser("evidence-for", help="Find sources supporting a claim")
    p_efor.add_argument("claim", help="The claim to find evidence for")

    p_eagainst = subparsers.add_parser("evidence-against", help="Find sources challenging a claim")
    p_eagainst.add_argument("claim", help="The claim to find evidence against")

    subparsers.add_parser("entities", help="List all extracted entities")

    p_rel = subparsers.add_parser("relationships", help="Show entity connections")
    p_rel.add_argument("entity", help="Entity name to look up")

    p_cov = subparsers.add_parser("coverage", help="Check entity coverage in a document")
    p_cov.add_argument("document", help="Path to document to check")

    # Queue-based ingestion
    subparsers.add_parser("serve", help="Start ingestion worker (long-running)")

    p_enqueue = subparsers.add_parser("enqueue", help="Add files to ingestion queue")
    p_enqueue.add_argument("files", nargs="+", help="File paths to enqueue")
    p_enqueue.add_argument("--reindex", action="store_true",
                           help="Force re-processing of already-ingested files")

    subparsers.add_parser("status", help="Show ingestion queue status")

    p_drain = subparsers.add_parser("drain", help="Block until queue is fully processed")
    p_drain.add_argument("--timeout", type=int, default=0,
                         help="Timeout in seconds (0 = wait indefinitely)")

    subparsers.add_parser("stop", help="Stop the ingestion worker")

    args = parser.parse_args()

    commands = {
        "build": cmd_build,
        "update": cmd_update,
        "query": cmd_query,
        "contradictions": cmd_contradictions,
        "evidence-for": cmd_evidence_for,
        "evidence-against": cmd_evidence_against,
        "entities": cmd_entities,
        "relationships": cmd_relationships,
        "coverage": cmd_coverage,
        "serve": cmd_serve,
        "enqueue": cmd_enqueue,
        "status": cmd_queue_status,
        "drain": cmd_drain,
        "stop": cmd_stop,
    }

    asyncio.run(commands[args.command](args))


if __name__ == "__main__":
    main()
